CREATE TABLE TBL_ASSOCIADOS (
  id_associado INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  dc_cpf VARCHAR(20) NULL,
  nm_associado VARCHAR(255) NULL,
  PRIMARY KEY(id_associado)
);

CREATE TABLE TBL_CONTABILIZACAO (
  id_contabilizacao INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  TBL_ASSOCIADOS_id_associado INTEGER UNSIGNED NOT NULL,
  TBL_PAUTA_id_pauta INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(id_contabilizacao),
  INDEX TBL_CONTABILIZACAO_FKIndex1(TBL_PAUTA_id_pauta),
  INDEX TBL_CONTABILIZACAO_FKIndex2(TBL_ASSOCIADOS_id_associado)
);

CREATE TABLE TBL_PAUTA (
  id_pauta INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  nm_pauta VARCHAR(255) NULL,
  PRIMARY KEY(id_pauta)
);

CREATE TABLE TBL_CONTABILIZACAO (
  id_contabilizacao INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  id_associado INTEGER UNSIGNED NULL,
  id_pauta INTEGER UNSIGNED NULL,
  dc_voto VARCHAR(10) NULL,
  PRIMARY KEY(id_contabilizacao)
);


